// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GenerateArticle(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function GetAIProviders():Promise<Array<string>>;

export function GetAppStatus():Promise<string>;

export function GetSettings():Promise<string>;

export function ListTasks():Promise<string>;

export function LoadLastArticle():Promise<string>;

export function PublishArticle(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function RemoveTask(arg1:number):Promise<string>;

export function SaveLastArticle(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<string>;

export function SearchImages(arg1:string,arg2:number):Promise<string>;
