// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddScheduledTask'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateArticle(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateArticle'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAIProviders() {
  return window['go']['main']['App']['GetAIProviders']();
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function LoadLastArticle() {
  return window['go']['main']['App']['LoadLastArticle']();
}

export function PublishArticle(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PublishArticle'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function SaveLastArticle(arg1, arg2) {
  return window['go']['main']['App']['SaveLastArticle'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchImages(arg1, arg2) {
  return window['go']['main']['App']['SearchImages'](arg1, arg2);
}
